### PR TITLE
Infra structure scan entries

### PR DESCRIPTION
**Pull request by nameisaravind**
This is to inline with Infra structure scan entries.

### CODE REVIEW

**Review by rvema — APPROVED** [review]
lgtm

**Comment by rvema** [comment]
@nameisaravind please update your branch

**Review by nireeshT — CHANGES_REQUESTED** [review]
bump version to 3.14.20

**Review by rvema — CHANGES_REQUESTED** [review]
Please update your branch

**Review by nireeshT — APPROVED** [review]

**Review by rvema — APPROVED** [review]
lgtm

**Pull request merged**
