### PR TITLE
Deleted SonarProfileRepository.java

### PR DESCRIPTION
**Pull request by jar145**
Deleted this file as it exists in the Sonar collector already. The Jenkins build collector is unable to run with this file and works fine without it as well as the sonar collector.

Fixes: https://github.com/Hygieia/hygieia-build-jenkins-collector/issues/20

**Affects:** 3.9.6.

---

### CODE REVIEW

**Comment by rvema** [comment]
@jar145 Since this is a change on common library, we need to check if this does not break the components. Ideally this repository file should have been packaged with the tool specific implementation and will take care of this during the upgrade effort. [hygieia-api](https://github.com/hygieia/hygieia-api)

**Comment by jar145** [comment]
@rvema I don't think I quite understand. The repository file is already packaged with the tool-specific implementation so I'm not sure how the upgrade effort would change anything.

**Comment by rvema** [comment]
@jar145 need to check if the project [api](https://github.com/hygieia/api) is currently using this repository? can you download api project and see if api project compiles fine with your core changes ?

**Comment by jar145** [comment]
@rvema yes I had already verified that api works with the core change as of version 3.9.6. I also confirmed the same with the most recent core version (3.9.8) with that change and the api compiles and runs successfully.

**Review by rvema — APPROVED** [review]
lgtm

**Pull request merged**
